# Generated by Django 5.2 on 2025-09-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysis_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Strategy configuration'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='risk_config',
            field=models.JSONField(blank=True, default=dict, help_text='Risk configuration'),
        ),
    ]
