# Generated by Django 5.2 on 2025-12-24 15:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_margin_models'),
        ('clients', '0003_alter_customuser_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction ID (UUID or Binance ID)', max_length=64, unique=True)),
                ('binance_order_id', models.CharField(blank=True, db_index=True, help_text='Binance order/transaction ID', max_length=64, null=True)),
                ('transaction_type', models.CharField(choices=[('SPOT_BUY', 'Spot Buy'), ('SPOT_SELL', 'Spot Sell'), ('MARGIN_BUY', 'Margin Buy'), ('MARGIN_SELL', 'Margin Sell'), ('MARGIN_BORROW', 'Margin Borrow'), ('MARGIN_REPAY', 'Margin Repay'), ('TRANSFER_TO_MARGIN', 'Transfer to Margin'), ('TRANSFER_FROM_MARGIN', 'Transfer from Margin'), ('STOP_LOSS_PLACED', 'Stop-Loss Placed'), ('STOP_LOSS_TRIGGERED', 'Stop-Loss Triggered'), ('STOP_LOSS_CANCELLED', 'Stop-Loss Cancelled'), ('TAKE_PROFIT_PLACED', 'Take-Profit Placed'), ('TAKE_PROFIT_TRIGGERED', 'Take-Profit Triggered'), ('LIQUIDATION', 'Liquidation'), ('INTEREST_CHARGED', 'Interest Charged'), ('FEE_PAID', 'Fee Paid')], db_index=True, help_text='Type of transaction', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', help_text='Transaction status', max_length=20)),
                ('symbol', models.CharField(db_index=True, help_text='Trading pair (e.g., BTCUSDC)', max_length=20)),
                ('asset', models.CharField(help_text='Asset involved (e.g., BTC, USDC)', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Quantity of asset', max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, help_text='Price per unit', max_digits=20, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=8, help_text='Total value (quantity × price)', max_digits=20, null=True)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Transaction fee', max_digits=20)),
                ('fee_asset', models.CharField(blank=True, help_text='Asset used for fee payment', max_length=10, null=True)),
                ('side', models.CharField(blank=True, help_text='BUY or SELL', max_length=10, null=True)),
                ('leverage', models.PositiveSmallIntegerField(blank=True, help_text='Leverage used (for margin trades)', null=True)),
                ('is_isolated_margin', models.BooleanField(default=False, help_text='Whether this is an isolated margin transaction')),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, help_text='Stop-loss price (if applicable)', max_digits=20, null=True)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=8, help_text='Risk amount (if applicable)', max_digits=20, null=True)),
                ('risk_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Risk as percentage of capital', max_digits=5, null=True)),
                ('description', models.TextField(help_text='Human-readable description of the transaction')),
                ('raw_response', models.JSONField(blank=True, help_text='Raw API response from Binance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('executed_at', models.DateTimeField(blank=True, help_text='When the transaction was executed on exchange', null=True)),
                ('source', models.CharField(default='robson', help_text='Source of transaction (robson, binance_sync, manual)', max_length=50)),
                ('client', models.ForeignKey(help_text='Client who owns this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='audit_transactions', to='clients.client')),
                ('related_order', models.ForeignKey(blank=True, help_text='Related order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_transactions', to='api.order')),
                ('related_position', models.ForeignKey(blank=True, help_text='Related margin position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.marginposition')),
            ],
            options={
                'verbose_name': 'Audit Transaction',
                'verbose_name_plural': 'Audit Transactions',
                'db_table': 'api_audit_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='api_audit_t_client__58781d_idx'), models.Index(fields=['transaction_type', 'created_at'], name='api_audit_t_transac_0131cb_idx'), models.Index(fields=['symbol', 'created_at'], name='api_audit_t_symbol_157c9c_idx'), models.Index(fields=['status', 'created_at'], name='api_audit_t_status_91318f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(db_index=True, help_text='When this snapshot was taken')),
                ('spot_usdc', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('spot_btc', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('margin_btc_free', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('margin_btc_borrowed', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('margin_usdc_free', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('margin_usdc_borrowed', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('btc_price', models.DecimalField(decimal_places=8, help_text='BTC price at snapshot time', max_digits=20)),
                ('total_equity', models.DecimalField(decimal_places=8, help_text='Total equity in USDC', max_digits=20)),
                ('margin_level', models.DecimalField(blank=True, decimal_places=4, help_text='Margin level at snapshot', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_snapshots', to='clients.client')),
            ],
            options={
                'verbose_name': 'Balance Snapshot',
                'verbose_name_plural': 'Balance Snapshots',
                'db_table': 'api_balance_snapshot',
                'ordering': ['-snapshot_time'],
                'indexes': [models.Index(fields=['client', 'snapshot_time'], name='api_balance_client__6d0cd8_idx')],
            },
        ),
    ]
