# Generated by Django 5.2 on 2025-12-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tradingintent_policystate'),
        ('clients', '0005_waitlistentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Transaction (Movement)', 'verbose_name_plural': 'Audit Transactions (Movements)'},
        ),
        migrations.AddField(
            model_name='audittransaction',
            name='account_type',
            field=models.CharField(choices=[('SPOT', 'Spot Account'), ('ISOLATED_MARGIN', 'Isolated Margin Account'), ('CROSS_MARGIN', 'Cross Margin Account'), ('FUTURES', 'Futures Account')], db_index=True, default='SPOT', help_text='Which account this movement affects (Spot, Isolated Margin, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='audittransaction',
            name='category',
            field=models.CharField(choices=[('TRADING', 'Trading (Buy/Sell)'), ('TRANSFER', 'Transfer (Between Accounts)'), ('CREDIT', 'Credit (Borrow/Repay)'), ('ORDER', 'Order Lifecycle'), ('FEE', 'Fees & Interest'), ('RISK', 'Risk Events')], db_index=True, default='TRADING', help_text='High-level category of this movement', max_length=20),
        ),
        migrations.AddField(
            model_name='audittransaction',
            name='related_operation',
            field=models.ForeignKey(blank=True, help_text='The Operation (trade cycle) this movement belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='api.operation'),
        ),
        migrations.AlterField(
            model_name='audittransaction',
            name='related_order',
            field=models.ForeignKey(blank=True, help_text='Related order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='api.order'),
        ),
        migrations.AlterField(
            model_name='audittransaction',
            name='related_position',
            field=models.ForeignKey(blank=True, help_text='Related margin position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='api.marginposition'),
        ),
        migrations.AlterField(
            model_name='audittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SPOT_BUY', 'Spot Buy'), ('SPOT_SELL', 'Spot Sell'), ('MARGIN_BUY', 'Margin Buy'), ('MARGIN_SELL', 'Margin Sell'), ('TRANSFER_SPOT_TO_ISOLATED', 'Transfer Spot → Isolated Margin'), ('TRANSFER_ISOLATED_TO_SPOT', 'Transfer Isolated Margin → Spot'), ('TRANSFER_TO_MARGIN', 'Transfer to Margin'), ('TRANSFER_FROM_MARGIN', 'Transfer from Margin'), ('MARGIN_BORROW', 'Margin Borrow'), ('MARGIN_REPAY', 'Margin Repay'), ('INTEREST_CHARGED', 'Interest Charged'), ('STOP_LOSS_PLACED', 'Stop-Loss Placed'), ('STOP_LOSS_TRIGGERED', 'Stop-Loss Triggered'), ('STOP_LOSS_CANCELLED', 'Stop-Loss Cancelled'), ('TAKE_PROFIT_PLACED', 'Take-Profit Placed'), ('TAKE_PROFIT_TRIGGERED', 'Take-Profit Triggered'), ('LIMIT_ORDER_PLACED', 'Limit Order Placed'), ('LIMIT_ORDER_FILLED', 'Limit Order Filled'), ('LIMIT_ORDER_CANCELLED', 'Limit Order Cancelled'), ('TRADING_FEE', 'Trading Fee'), ('FEE_PAID', 'Fee Paid'), ('LIQUIDATION', 'Liquidation'), ('MARGIN_CALL', 'Margin Call Warning')], db_index=True, help_text='Type of transaction', max_length=30),
        ),
        migrations.AddIndex(
            model_name='audittransaction',
            index=models.Index(fields=['account_type', 'created_at'], name='api_audit_t_account_4eb212_idx'),
        ),
        migrations.AddIndex(
            model_name='audittransaction',
            index=models.Index(fields=['category', 'created_at'], name='api_audit_t_categor_b2632e_idx'),
        ),
        migrations.AddIndex(
            model_name='audittransaction',
            index=models.Index(fields=['related_operation', 'created_at'], name='api_audit_t_related_159593_idx'),
        ),
    ]
