# Generated by Django 5.2 on 2025-12-28 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_generalize_outbox_for_commands_and_events'),
        ('clients', '0005_waitlistentry'),
    ]

    operations = [
        # Rename CircuitBreakerState model (no DB changes - same db_table)
        migrations.RenameModel(
            old_name='CircuitBreakerState',
            new_name='CircuitBreakerStateModel',
        ),
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Feature vector timestamp (UTC)')),
                ('symbol', models.CharField(db_index=True, help_text='Trading pair (e.g., BTCUSDT)', max_length=20)),
                ('features', models.JSONField(default=dict, help_text='Computed features as key-value pairs')),
                ('logic_version', models.CharField(help_text="Feature computation logic version (e.g., 'v1.0.0')", max_length=20)),
                ('client', models.ForeignKey(blank=True, help_text='Client that owns this record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
            options={
                'verbose_name': 'Market Feature Vector',
                'verbose_name_plural': 'Market Feature Vectors',
                'db_table': 'market_feature_vectors',
                'ordering': ['-timestamp', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='MarketContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Snapshot timestamp (UTC)')),
                ('symbol', models.CharField(db_index=True, help_text='Trading pair (e.g., BTCUSDT)', max_length=20)),
                ('market_regime', models.CharField(help_text='Classified market regime', max_length=20)),
                ('risk_bias', models.CharField(help_text='Risk bias classification', max_length=20)),
                ('context_data', models.JSONField(default=dict, help_text='Full context snapshot with all signals')),
                ('logic_version', models.CharField(help_text="Classification logic version (e.g., 'v1.0.0')", max_length=20)),
                ('client', models.ForeignKey(blank=True, help_text='Client that owns this record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
            options={
                'verbose_name': 'Market Context Snapshot',
                'verbose_name_plural': 'Market Context Snapshots',
                'db_table': 'market_context_snapshots',
                'ordering': ['-timestamp', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Metric timestamp (UTC, truncated to seconds)')),
                ('symbol', models.CharField(db_index=True, help_text='Trading pair (e.g., BTCUSDT)', max_length=20)),
                ('metric_name', models.CharField(db_index=True, help_text='Metric type: funding_rate, open_interest, mark_price, index_price, next_funding_time, tvl, active_addresses, gas_price, etc.', max_length=50)),
                ('source', models.CharField(db_index=True, help_text='Data source: binance_futures, binance_spot, defillama, glassnode, coinmetrics, etc.', max_length=50)),
                ('value', models.DecimalField(decimal_places=18, help_text='Metric value with high precision. Examples: 0.000100000000000000 (funding rate 0.01%), 1234567.890000000000000000 (open interest in contracts), 95432.100000000000000000 (mark price in USDT)', max_digits=30)),
                ('tags', models.JSONField(blank=True, default=dict, help_text='Optional metadata for context. Examples: {"timeframe": "8h", "contract": "perpetual"}, {"chain": "ethereum", "protocol": "uniswap"}')),
                ('collection_metadata', models.JSONField(blank=True, default=dict, help_text='Collection context for debugging. Examples: {"collector_version": "1.0.0", "api_latency_ms": 120, "retry_count": 0}')),
                ('client', models.ForeignKey(blank=True, help_text='Client that owns this record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
            options={
                'verbose_name': 'Market Metric Point',
                'verbose_name_plural': 'Market Metric Points',
                'db_table': 'market_metric_points',
                'ordering': ['-timestamp', 'symbol', 'metric_name'],
            },
        ),
        migrations.AlterField(
            model_name='operation',
            name='stop_check_count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of times stop monitor has checked this operation', null=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='exchange',
            field=models.CharField(default='stop_events', help_text='RabbitMQ exchange name', max_length=100),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='outbox_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique outbox entry identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopevent',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique event identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopexecution',
            name='execution_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique execution identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopexecution',
            name='source',
            field=models.CharField(choices=[('ws', 'WebSocket Service'), ('cron', 'CronJob Backstop'), ('manual', 'Manual Intervention')], db_index=True, help_text='Which component executed this', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='client',
            field=models.OneToOneField(help_text='Associated client/tenant', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='risk_config', serialize=False, to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='featurevector',
            index=models.Index(fields=['client', 'symbol', '-timestamp'], name='idx_features_latest'),
        ),
        migrations.AlterUniqueTogether(
            name='featurevector',
            unique_together={('client', 'symbol', 'timestamp', 'logic_version')},
        ),
        migrations.AddIndex(
            model_name='marketcontextsnapshot',
            index=models.Index(fields=['client', 'symbol', '-timestamp'], name='idx_context_latest'),
        ),
        migrations.AlterUniqueTogether(
            name='marketcontextsnapshot',
            unique_together={('client', 'symbol', 'timestamp', 'logic_version')},
        ),
        migrations.AddIndex(
            model_name='metricpoint',
            index=models.Index(fields=['client', 'symbol', 'timestamp'], name='idx_metric_symbol_time'),
        ),
        migrations.AddIndex(
            model_name='metricpoint',
            index=models.Index(fields=['client', 'metric_name', 'timestamp'], name='idx_metric_name_time'),
        ),
        migrations.AddIndex(
            model_name='metricpoint',
            index=models.Index(fields=['client', 'source', 'symbol', 'metric_name', '-timestamp'], name='idx_metric_latest'),
        ),
        migrations.AlterUniqueTogether(
            name='metricpoint',
            unique_together={('client', 'source', 'symbol', 'metric_name', 'timestamp')},
        ),
    ]
