# Generated by Django 5.2 on 2025-12-31 17:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_adr_0018_pattern_deduplication'),
        ('clients', '0005_waitlistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPatternConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this record is active')),
                ('auto_entry_enabled', models.BooleanField(default=False, help_text='Enable auto-entry for this pattern+strategy combination')),
                ('entry_mode', models.CharField(choices=[('SUGGEST', 'Suggest Only (User Confirms)'), ('AUTO', 'Auto-Entry (Requires Acknowledgement)')], default='SUGGEST', help_text='SUGGEST_ONLY: User must confirm. AUTO_ENTRY: Automatic entry.', max_length=16)),
                ('min_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.70'), help_text='Minimum pattern confidence [0-1] to trigger entry', max_digits=5)),
                ('max_entries_per_day', models.PositiveIntegerField(default=3, help_text='Maximum entries per day for this pattern+strategy')),
                ('max_entries_per_week', models.PositiveIntegerField(default=10, help_text='Maximum entries per week for this pattern+strategy')),
                ('cooldown_minutes', models.PositiveIntegerField(default=60, help_text='Cooldown between entries for same pattern (minutes)')),
                ('position_size_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Position size as % of capital (overrides strategy default)', max_digits=5, null=True)),
                ('require_confirmation', models.BooleanField(default=True, help_text='Require pattern confirmation before entry')),
                ('timeframes', models.JSONField(blank=True, default=list, help_text="List of allowed timeframes (empty = all). E.g., ['15m', '1h']")),
                ('symbols', models.JSONField(blank=True, default=list, help_text="List of allowed symbols (empty = all). E.g., ['BTCUSDT', 'ETHUSDT']")),
                ('require_volume_confirmation', models.BooleanField(default=False, help_text='Require above-average volume on breakout')),
                ('only_with_trend', models.BooleanField(default=False, help_text='Only enter if pattern aligns with higher timeframe trend')),
            ],
            options={
                'verbose_name': 'Strategy Pattern Config',
                'verbose_name_plural': 'Strategy Pattern Configs',
            },
        ),
        migrations.AlterModelOptions(
            name='patternalert',
            options={'ordering': ['-alert_ts'], 'verbose_name': 'Pattern Alert', 'verbose_name_plural': 'Pattern Alerts'},
        ),
        migrations.AlterModelOptions(
            name='patterninstance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pattern Instance', 'verbose_name_plural': 'Pattern Instances'},
        ),
        migrations.RenameIndex(
            model_name='patterninstance',
            new_name='api_pattern_client__02b658_idx',
            old_name='api_pattern_client_idx',
        ),
        migrations.AlterField(
            model_name='circuitbreakerstatemodel',
            name='symbol',
            field=models.CharField(help_text='Trading pair (e.g., BTCUSDC)', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrygateconfig',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client that owns this record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='entrygatedecisionmodel',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client that owns this record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='aggregate_id',
            field=models.BigIntegerField(db_index=True, help_text='Operation ID (for correlation)'),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='aggregate_type',
            field=models.CharField(db_index=True, help_text="Message type: 'stop_command' or 'stop_event'", max_length=50),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='correlation_id',
            field=models.CharField(db_index=True, help_text='Global idempotency key (format: {operation_id}:{stop_price}:{timestamp_ms})', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='event_type',
            field=models.CharField(db_index=True, help_text="Semantic type: 'COMMAND_ISSUED', 'EVENT_TRIGGERED', 'EXECUTED', etc.", max_length=50),
        ),
        migrations.AlterField(
            model_name='patternalert',
            name='alert_ts',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='patternalert',
            index=models.Index(fields=['instance', 'alert_type', 'alert_ts'], name='api_pattern_instanc_122778_idx'),
        ),
        migrations.AddField(
            model_name='strategypatternconfig',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client that owns this record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AddField(
            model_name='strategypatternconfig',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_configs', to='api.patterncatalog'),
        ),
        migrations.AddField(
            model_name='strategypatternconfig',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_configs', to='api.strategy'),
        ),
        migrations.AddIndex(
            model_name='strategypatternconfig',
            index=models.Index(fields=['strategy', 'auto_entry_enabled'], name='api_strateg_strateg_19792d_idx'),
        ),
        migrations.AddIndex(
            model_name='strategypatternconfig',
            index=models.Index(fields=['pattern', 'auto_entry_enabled'], name='api_strateg_pattern_710a26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategypatternconfig',
            unique_together={('strategy', 'pattern')},
        ),
    ]
