# Generated by Django 5.2 on 2025-12-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_strategypatternconfig_alter_patternalert_options_and_more'),
        ('clients', '0005_waitlistentry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patterninstance',
            name='unique_pattern_instance',
        ),
        migrations.AddConstraint(
            model_name='patterninstance',
            constraint=models.UniqueConstraint(fields=('client', 'pattern', 'symbol', 'timeframe', 'start_ts'), name='unique_pattern_instance', nulls_distinct=False, violation_error_message='A pattern instance with these attributes already exists.'),
        ),
    ]
