# Generated by Django 5.2 on 2026-01-01 05:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_fix_unique_constraint_nulls_distinct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingintent',
            name='capital',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Capital allocated for this intent', max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingintent',
            name='execution_result',
            field=models.JSONField(blank=True, help_text='ExecutionResult.to_dict() result', null=True),
        ),
        migrations.AddField(
            model_name='tradingintent',
            name='validation_result',
            field=models.JSONField(blank=True, help_text='ValidationReport.to_dict() result', null=True),
        ),
    ]
