# Generated by Django 5.2 on 2026-01-02 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_pattern_trigger_mvp'),
        ('clients', '0005_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='trading_intent',
            field=models.OneToOneField(blank=True, help_text='TradingIntent that created this operation (agentic workflow only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation', to='api.tradingintent'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['client', 'status', 'created_at'], name='operation_portfolio_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['trading_intent'], name='operation_intent_idx'),
        ),
    ]
