# Generated by Django 5.2 on 2026-01-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_link_operation_to_tradingintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='market_bias',
            field=models.CharField(choices=[('BULLISH', 'Bullish - Buy/Long positions'), ('BEARISH', 'Bearish - Sell/Short positions'), ('NEUTRAL', 'Neutral - Analyze market conditions')], default='BULLISH', help_text='Market direction bias for this strategy', max_length=20),
        ),
    ]
