# Generated by Codex on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_add_market_bias_to_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="marginposition",
            name="operation",
            field=models.OneToOneField(
                blank=True,
                help_text="Related Operation (Level 2) for this margin position",
                null=True,
                on_delete=models.SET_NULL,
                related_name="margin_position",
                to="api.operation",
            ),
        ),
    ]
