# Generated by Django 5.2 on 2026-01-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_operation_to_margin_position'),
        ('clients', '0005_waitlistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingThesisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this record is active')),
                ('title', models.CharField(max_length=255)),
                ('symbol', models.CharField(help_text='Trading symbol (e.g., BTCUSDT)', max_length=20)),
                ('timeframe', models.CharField(help_text='Timeframe (e.g., 4h, 1d)', max_length=10)),
                ('market_context', models.TextField(help_text='What is happening in the market')),
                ('rationale', models.TextField(help_text='Why this opportunity might exist')),
                ('expected_trigger', models.TextField(help_text='What needs to happen to confirm')),
                ('invalidation', models.TextField(help_text='What proves the thesis wrong')),
                ('hypothesis_type', models.CharField(blank=True, help_text='Type: breakout, mean_reversion, trend_following, etc.', max_length=50, null=True)),
                ('confidence_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Confidence level in the thesis', max_length=20, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft - Being created/refined'), ('active', 'Active - Monitoring for trigger/invalidation'), ('validated', 'Validated - Trigger occurred, thesis was correct'), ('rejected', 'Rejected - Invalidation occurred, thesis was wrong'), ('expired', 'Expired - Time-based expiry'), ('converted', 'Converted - Converted to executable strategy')], db_index=True, default='draft', help_text='Current status of the thesis', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, help_text='When the thesis was validated', null=True)),
                ('converted_to_strategy_id', models.CharField(blank=True, help_text='ID of strategy if converted', max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client that owns this record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
            options={
                'verbose_name': 'Trading Thesis',
                'verbose_name_plural': 'Trading Theses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status', 'created_at'], name='thesis_client_status_idx'), models.Index(fields=['symbol', 'status'], name='thesis_symbol_status_idx')],
            },
        ),
    ]
