apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: robson-backend-gateway
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: {{ .Values.host | quote }}
      allowedRoutes:
        namespaces:
          from: Same

