FROM python:3.10-slim-buster
RUN apt-get update && apt-get install -y gcc
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY ../requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . /app/
EXPOSE 8000
CMD gunicorn -b 0.0.0.0:8080 --worker-class=gevent --worker-connections=1000 --workers=5 backend.wsgi
