# yamllint configuration for Robson Bot

extends: default

rules:
  # Line length - allow longer lines for readability
  line-length:
    max: 120
    level: warning

  # Indentation - 2 spaces (Kubernetes/Helm standard)
  indentation:
    spaces: 2
    indent-sequences: true

  # Allow inline mappings (useful for Kubernetes resources)
  braces:
    max-spaces-inside: 1

  # Comments - require space after #
  comments:
    min-spaces-from-content: 1

  # Document start (---) not required
  document-start: disable

  # Truthy values - allow yes/no (common in Ansible/K8s)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Empty values - allow
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

# Ignore patterns
ignore: |
  .github/
  node_modules/
  venv/
  .venv/
