FROM python:3.12-slim-bookworm
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential gcc \
    && rm -rf /var/lib/apt/lists/*
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_MODULES_SETTINGS=backend.settings
ENV DEBUG=True
WORKDIR /app
COPY ../requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . /app/
EXPOSE 8000
CMD ["gunicorn","-b","0.0.0.0:8000","--worker-class=gevent","--worker-connections=1000","--workers=5","backend.wsgi"]
