# Generated by Django 5.2 on 2025-12-21 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='clients.client'),
        ),
    ]
