# Generated by Django 5.2 on 2025-12-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_customuser_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='demo_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='demo_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_demo_account',
            field=models.BooleanField(default=False),
        ),
    ]
