apiVersion: v1
kind: Namespace
metadata:
  name: dns
  labels:
    name: dns
    app.kubernetes.io/name: dns-infrastructure
    app.kubernetes.io/component: authoritative-dns
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
