# Generated by Django 5.2 on 2025-04-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
