apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-ambient
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.22.1
    helm:
      values: |
        pilot:
          env:
            PILOT_ENABLE_AMBIENT: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
