name: Preview Images (non-main)

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Compute tags
        id: vars
        run: |
          BRANCH=${GITHUB_REF_NAME}
          SHA=${GITHUB_SHA::7}
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "short_sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push backend image (branch)
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./apps/backend/monolith
          file: ./apps/backend/monolith/docker/Dockerfile_django
          push: true
          tags: |
            ldamasio/rbs-backend-monolith-prod:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.short_sha }}

      - name: Build and push frontend image (branch)
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./apps/frontend
          file: ./apps/frontend/docker/Dockerfile
          push: true
          tags: |
            ldamasio/rbs-frontend-prod:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.short_sha }}

