name: Robson Production Pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Create SSH key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

      - name: Remove old files
        shell: bash
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_PATH: ${{ secrets.APP_PATH }}
        run: ssh
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no
          -i ../private.key
          -v
          "${USERNAME}@${HOST}"
          "ls -la"


      # - name: Executing remote command
      #   uses: appleboy/ssh-action@master
      #   env:
      #     APP_PATH: ${{ secrets.APP_PATH }}
      #   with:
      #     HOST: ${{ secrets.HOST }}
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PORT: ${{ secrets.PORT }}
      #     KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /app/rbs/src
      #       ls -la
      #       echo "Deploy finalizado"
